"""Initial schema, reset 2026-09-15.

This replaces the original 0001-0034 (4,388 lines across 35 files, including a
merge migration and a duplicated 0015 from an old branch collision). Squashing
was tried first and made things worse: four interleaved RunPython operations
act as optimizer barriers, so `squashmigrations` collapsed 353 operations to
349 and produced a 2,203-line file that would have had to sit *alongside* the
originals until every install had applied it.

Upgrading a pre-reset database needs nothing special — a normal `migrate` is
enough. The replaced 0001 was also named `0001_initial`, so Django reads it as
already applied and plans only 0002 and 0003, both of which are idempotent
(`get_or_create` and `createcachetable`). The stale 0004-0034 rows left in
django_migrations are ignored. Verified on a copy of a fully-migrated database,
including a canary row, and the resulting schema compared against a fresh
install across 678 columns, indexes and constraints — identical.

Two data migrations were carried across because a fresh database still needs
them: the GebüH Ziffern seed (0002) and the cache table (0003). Two historical
data fixes were dropped instead, since they are no-ops on a fresh database and
have long since run on existing ones: retiring the missing-session-log tag, and
migrating supervision notes into SupervisionItems.

Left in the compact form `makemigrations` emits: `ruff format` expands it to
3,106 lines by splitting nearly every field definition, which is why
`*/migrations/*` is excluded in pyproject.toml. See `force-exclude` there for
why that exclusion did not hold for the pre-commit hook.
"""

# Generated by Django 6.1.1 on 2026-09-15 18:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import my_practice.fields
import my_practice.models.bank_statement
import my_practice.models.calendar
import my_practice.models.client
import my_practice.models.financial
import my_practice.models.inquiry
import my_practice.models.invoice
import my_practice.models.operational
import my_practice.models.tag
import my_practice.models.timeoff
import my_practice.models.todo
import my_practice.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_code', models.CharField(help_text='2-3 letter client initials (e.g., DE, JM)', max_length=10, unique=True, verbose_name='Client code')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('first_seen_date', models.DateField(blank=True, help_text='Date of the first intro session/appointment', null=True, verbose_name='First appointment')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('cost_carrier', models.CharField(blank=True, help_text="Cost carrier / health insurance (e.g. 'self-pay', 'Allianz PKV')", max_length=200, verbose_name='Cost carrier')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('intake_sent_date', models.DateField(blank=True, help_text='Date the intake form was handed out/sent', null=True, verbose_name='Intake form handed out')),
                ('contract_signed_date', models.DateField(blank=True, help_text='Date the treatment contract was signed', null=True, verbose_name='Contract signed')),
                ('questionnaire_sent_date', models.DateField(blank=True, help_text='Date the anamnesis questionnaire was handed out/sent', null=True, verbose_name='Questionnaire handed out')),
                ('onboarding_complete_date', models.DateField(blank=True, help_text='Date the entire onboarding process was completed', null=True, verbose_name='Onboarding complete')),
                ('hourly_rate_60', models.DecimalField(decimal_places=2, default=Decimal('90.00'), help_text='Rate for 60-minute session', max_digits=6, verbose_name='Hourly rate (60 min)')),
                ('hourly_rate_90', models.DecimalField(decimal_places=2, default=Decimal('130.00'), help_text='Rate for 90-minute session', max_digits=6, verbose_name='Hourly rate (90 min)')),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Cancellation fee')),
                ('language', models.CharField(choices=[(my_practice.models.client.Client.Language['DE'], 'German'), (my_practice.models.client.Client.Language['EN'], 'English')], default=my_practice.models.client.Client.Language['DE'], max_length=2, verbose_name='Preferred language')),
                ('salutation', models.CharField(blank=True, help_text="Custom salutation for emails (e.g., 'Dear John', 'Liebe Maria'). If empty, will use 'Dear {name}' (EN) or 'Liebe:r {name}' (DE).", max_length=100, verbose_name='Email salutation')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('needs_gebueh_invoice', models.BooleanField(default=False, help_text='GebüH-Ziffern und Diagnose auf der Rechnung ausweisen (PKV / Beihilfe)', verbose_name='GebüH-Rechnung')),
                ('gebueh_no_diagnosis', models.BooleanField(default=False, help_text='Omit the diagnosis line from GebüH invoices for this client', verbose_name='No diagnosis on invoice')),
                ('is_online_client', models.BooleanField(default=False, help_text='Check if this client primarily has online sessions', verbose_name='Online client')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-active', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Tag name (e.g., 'missing-paperwork', 'follow-up')", max_length=50, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(help_text='URL-friendly version of the name (auto-generated)', unique=True, verbose_name='Slug')),
                ('color', models.CharField(choices=[(my_practice.models.tag.ClientTag.Color['RED'], 'Red'), (my_practice.models.tag.ClientTag.Color['ORANGE'], 'Orange'), (my_practice.models.tag.ClientTag.Color['YELLOW'], 'Yellow'), (my_practice.models.tag.ClientTag.Color['GREEN'], 'Green'), (my_practice.models.tag.ClientTag.Color['BLUE'], 'Blue'), (my_practice.models.tag.ClientTag.Color['PURPLE'], 'Purple'), (my_practice.models.tag.ClientTag.Color['PINK'], 'Pink'), (my_practice.models.tag.ClientTag.Color['GRAY'], 'Gray')], default='blue', help_text='Display color for the tag', max_length=20, verbose_name='Color')),
                ('category', models.CharField(choices=[(my_practice.models.tag.ClientTag.Category['GENERAL'], 'General'), (my_practice.models.tag.ClientTag.Category['ATTENTION'], 'Needs attention'), (my_practice.models.tag.ClientTag.Category['EXIT'], 'Exit reasons')], default='general', help_text='Tag category: General (informational), Needs Attention (priority), or Exit Reasons (documentation)', max_length=20, verbose_name='Category')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this tag represents', verbose_name='Description')),
                ('is_system', models.BooleanField(default=False, help_text="System-generated tags (like 'no-next-session') cannot be manually edited", verbose_name='System tag')),
            ],
            options={
                'verbose_name': 'Client tag',
                'verbose_name_plural': 'Client tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter amount as a positive number', max_digits=10, verbose_name='Amount')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[(my_practice.models.financial.CompanyExpense.Category['MIETE'], 'Rent'), (my_practice.models.financial.CompanyExpense.Category['TELEFON'], 'Phone'), (my_practice.models.financial.CompanyExpense.Category['VERBAND'], 'Association / membership fees'), (my_practice.models.financial.CompanyExpense.Category['VERSICHERUNG'], 'Insurance'), (my_practice.models.financial.CompanyExpense.Category['KONTO'], 'Account / account fees'), (my_practice.models.financial.CompanyExpense.Category['WEBSEITE'], 'Website / domain'), (my_practice.models.financial.CompanyExpense.Category['WERBUNG'], 'Advertising / marketing'), (my_practice.models.financial.CompanyExpense.Category['SOFTWARE'], 'Software'), (my_practice.models.financial.CompanyExpense.Category['SELBSTERFAHRUNG'], 'Personal therapy (training)'), (my_practice.models.financial.CompanyExpense.Category['SUPERVISION'], 'Supervision'), (my_practice.models.financial.CompanyExpense.Category['TRAINING'], 'Training / continuing education'), (my_practice.models.financial.CompanyExpense.Category['AUSBILDUNG_ORT'], 'Training location'), (my_practice.models.financial.CompanyExpense.Category['GRUPPE'], 'Group'), (my_practice.models.financial.CompanyExpense.Category['MATERIALIEN'], 'Materials'), (my_practice.models.financial.CompanyExpense.Category['HARDWARE'], 'Hardware'), (my_practice.models.financial.CompanyExpense.Category['LITERATUR'], 'Literature'), (my_practice.models.financial.CompanyExpense.Category['KONGRESS'], 'Conference'), (my_practice.models.financial.CompanyExpense.Category['OTHER'], 'Other')], default=my_practice.models.financial.CompanyExpense.Category['OTHER'], max_length=30, verbose_name='Category')),
                ('has_invoice', models.BooleanField(default=False, verbose_name='Invoice available')),
                ('is_tax_deductible', models.BooleanField(default=True, verbose_name='Tax deductible')),
                ('is_filed_in_tax_return', models.BooleanField(default=False, verbose_name='Filed in tax return')),
            ],
            options={
                'verbose_name': 'Company Expense',
                'verbose_name_plural': 'Company Expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GebuhZiffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('bezeichnung', models.CharField(max_length=300, verbose_name='Description')),
                ('satz_max', models.DecimalField(decimal_places=2, help_text='Used for billing', max_digits=8, verbose_name='Maximum rate (€)')),
                ('satz_min', models.DecimalField(decimal_places=2, help_text='Reference value, not billed', max_digits=8, verbose_name='Minimum rate (€)')),
                ('anmerkung', models.TextField(blank=True, help_text='Billing notes (e.g. standalone service, frequency restriction)', verbose_name='Note')),
                ('max_haeufigkeit', models.PositiveSmallIntegerField(blank=True, help_text='Maximum count within the reference period', null=True, verbose_name='Max. frequency')),
                ('bezugszeitraum_tage', models.PositiveSmallIntegerField(blank=True, help_text='Period in days for the frequency check', null=True, verbose_name='Reference period (days)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Display order in the quick-entry list', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'GebüH billing code',
                'verbose_name_plural': 'GebüH billing codes',
                'ordering': ['sort_order', 'nummer'],
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Practitioner name')),
                ('slug', models.SlugField(default='default', help_text="Unique identifier for the practice (e.g. 'therapy', 'coaching')", unique=True, verbose_name='URL slug')),
                ('short_title_de', models.CharField(default='Therapie', help_text="Short label for the title bar, shown in the German UI (e.g. 'Therapie')", max_length=50, verbose_name='Short title (German)')),
                ('short_title_en', models.CharField(blank=True, default='Therapy', help_text="Short label for the title bar, shown in the English UI (e.g. 'Therapy')", max_length=50, verbose_name='Short title (English)')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive practices are not shown', verbose_name='Active')),
                ('title', models.CharField(default='Heilpraktiker für Psychotherapie', max_length=200, verbose_name='Professional title')),
                ('subtitle_de', models.CharField(blank=True, default='praxis für körperpsychotherapie', max_length=200, verbose_name='Subtitle (German)')),
                ('subtitle_en', models.CharField(blank=True, default='deutsch & english', max_length=200, verbose_name='Subtitle (English)')),
                ('street', models.CharField(default='', max_length=200, verbose_name='Street and house number')),
                ('postal_code', models.CharField(default='', max_length=20, verbose_name='Postal code')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('country', models.CharField(blank=True, default='Deutschland', max_length=100, verbose_name='Country')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('email_from_name', models.CharField(default='', help_text="Name displayed in 'From' field of outgoing emails", max_length=200, verbose_name='Email sender name')),
                ('website', models.URLField(default='', verbose_name='Website')),
                ('booking_url', models.URLField(blank=True, default='', help_text='Link to online appointment booking (e.g. Calendly). Automatically inserted into inquiry email templates.', verbose_name='Booking URL')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('bank_name', models.CharField(default='', max_length=200, verbose_name='Bank name')),
                ('iban', models.CharField(default='', max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(default='', max_length=11, verbose_name='BIC')),
                ('private_bank_account', models.CharField(blank=True, help_text='IBAN of the private account, for automatic detection of withdrawals and capital contributions during bank import', max_length=34, verbose_name='Private bank account (IBAN)')),
                ('csv_delimiter', models.CharField(default=';', help_text="Column separator used by your bank's CSV export, e.g. ';' or ','", max_length=1, verbose_name='CSV delimiter')),
                ('csv_column_date', models.CharField(default='Buchungstag', help_text="Header name of the booking date column in your bank's CSV export", max_length=100, verbose_name='CSV column: booking date')),
                ('csv_column_value_date', models.CharField(default='Valutadatum', help_text="Header name of the value date column in your bank's CSV export", max_length=100, verbose_name='CSV column: value date')),
                ('csv_column_payer_name', models.CharField(default='Name Zahlungsbeteiligter', help_text="Header name of the payer/payee name column in your bank's CSV export", max_length=100, verbose_name='CSV column: payer/payee name')),
                ('csv_column_payer_iban', models.CharField(default='IBAN Zahlungsbeteiligter', help_text="Header name of the payer/payee IBAN column in your bank's CSV export", max_length=100, verbose_name='CSV column: payer/payee IBAN')),
                ('csv_column_reference', models.CharField(default='Verwendungszweck', help_text="Header name of the payment reference column in your bank's CSV export", max_length=100, verbose_name='CSV column: payment reference')),
                ('csv_column_amount', models.CharField(default='Betrag', help_text="Header name of the transaction amount column in your bank's CSV export", max_length=100, verbose_name='CSV column: amount')),
                ('csv_column_balance', models.CharField(default='Saldo nach Buchung', help_text="Header name of the running balance column in your bank's CSV export", max_length=100, verbose_name='CSV column: balance after transaction')),
                ('csv_column_account_iban', models.CharField(default='IBAN Auftragskonto', help_text="Header name of the source account IBAN column in your bank's CSV export, used to verify the file belongs to this practice's account", max_length=100, verbose_name='CSV column: account IBAN')),
                ('overdue_after_days', models.PositiveIntegerField(default=30, help_text='Days after the invoice date before a sent invoice is flagged as overdue (dashboard widget, Focus Queue).', verbose_name='Overdue after (days)')),
                ('tax_id', models.CharField(default='', max_length=50, verbose_name='Tax ID')),
                ('is_kleinunternehmer', models.BooleanField(default=False, help_text='When enabled: § 19 UStG (small business) instead of § 4 No. 14 UStG (Heilpraktiker)', verbose_name='Kleinunternehmer regulation')),
                ('kleinunternehmer_text_de', models.TextField(default='Der Betrag ist umsatzsteuerfrei nach § 19 UStG (Kleinunternehmerregelung).', help_text="Used when 'Kleinunternehmer regulation' is enabled", verbose_name='Kleinunternehmer text (German)')),
                ('kleinunternehmer_text_en', models.TextField(blank=True, default='This amount is VAT-exempt according to § 19 UStG (small business regulation).', help_text="Used when 'Kleinunternehmer regulation' is enabled", verbose_name='Kleinunternehmer text (English)')),
                ('vat_exempt_text_de', models.TextField(default='Der Betrag ist umsatzsteuerfrei nach § 4 Nr. 14 UStG', help_text="Used when 'Kleinunternehmer regulation' is NOT enabled", verbose_name='VAT exemption text (German)')),
                ('vat_exempt_text_en', models.TextField(default='This amount is exempt from VAT according to § 4 No. 14 UStG', help_text="Used when 'Kleinunternehmer regulation' is NOT enabled", verbose_name='VAT exemption text (English)')),
                ('allows_free_form_items', models.BooleanField(default=False, help_text="Lets invoice items skip the linked session and use a free-text description instead — for day-rate or project billing that isn't tied to a therapy/coaching session. Leave off for therapy/coaching practices, where every invoice item must stay linked to a session.", verbose_name='Allow free-form invoice items')),
                ('memberships_de', models.TextField(blank=True, default='', verbose_name='Memberships (German)')),
                ('memberships_en', models.TextField(blank=True, default='', verbose_name='Memberships (English)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='practice/', verbose_name='Logo')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='practice/', verbose_name='Signature')),
                ('payment_terms_days', models.IntegerField(default=14, verbose_name='Payment term (days)')),
                ('payment_terms_text_de', models.CharField(default='Bitte überweisen Sie den Rechnungsbetrag unter Angabe der Rechnungsnummer innerhalb von 14 Tagen auf das unten genannte Konto.', max_length=200, verbose_name='Payment terms (German)')),
                ('payment_terms_text_en', models.CharField(default='Please transfer the invoice amount stating the invoice number within 14 days to the account mentioned below.', max_length=200, verbose_name='Payment terms (English)')),
                ('invoice_email_subject_de', models.CharField(default='Rechnung {invoice_number}', help_text='Placeholders: {invoice_number}, {amount}, {date}, {client_name}', max_length=200, validators=[my_practice.validators.validate_email_template_placeholders], verbose_name='Email subject (German)')),
                ('invoice_email_subject_en', models.CharField(default='Invoice {invoice_number}', help_text='Placeholders: {invoice_number}, {amount}, {date}, {client_name}', max_length=200, validators=[my_practice.validators.validate_email_template_placeholders], verbose_name='Email subject (English)')),
                ('invoice_email_body_de', models.TextField(default='{salutation},\n\n{sessions_intro}anbei erhalten Sie die Rechnung {invoice_number} über {amount} vom {date}.\n\nBitte überweisen Sie den Betrag innerhalb von 14 Tagen unter Angabe der Rechnungsnummer.\n\nDie Rechnung ist als PDF im Anhang beigefügt.', help_text='Placeholders: {salutation}, {sessions_intro}, {invoice_number}, {amount}, {date}, {client_name}', validators=[my_practice.validators.validate_email_template_placeholders], verbose_name='Email body (German)')),
                ('invoice_email_body_en', models.TextField(default='{salutation},\n\n{sessions_intro}Please find attached invoice {invoice_number} for {amount} dated {date}.\n\nPlease transfer the amount within 14 days, stating the invoice number.\n\nThe invoice is attached as a PDF.', help_text='Placeholders: {salutation}, {sessions_intro}, {invoice_number}, {amount}, {date}, {client_name}', validators=[my_practice.validators.validate_email_template_placeholders], verbose_name='Email body (English)')),
                ('email_signature', models.TextField(default='Mit freundlichen Grüßen / Best regards,\nHeilpraktiker für Psychotherapie', help_text='Used for all outgoing emails', verbose_name='Email signature')),
                ('commute_distance_km', models.PositiveIntegerField(blank=True, help_text='One-way distance in km (e.g. 12). Used for the distance allowance on the tax year summary.', null=True, verbose_name='Distance to practice (km)')),
                ('practice_weekdays', models.JSONField(blank=True, default=list, help_text='Weekdays on which the practice is attended (0=Mon, 1=Tue, 2=Wed, 3=Thu, 4=Fri).', verbose_name='Practice days (weekdays)')),
                ('monthly_target_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Target hours (sessions) per month, e.g. 60.0. Enables capacity monitoring on the dashboard.', max_digits=6, null=True, verbose_name='Monthly target: hours')),
                ('monthly_target_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Target revenue per month in €, e.g. 3000.00. Enables capacity monitoring on the dashboard.', max_digits=10, null=True, verbose_name='Monthly target: revenue (€)')),
            ],
            options={
                'verbose_name': 'Practice settings',
                'verbose_name_plural': 'Practice settings',
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('type', models.CharField(choices=[(my_practice.models.timeoff.TimeOff.Type['VACATION'], 'Urlaub / Vacation'), (my_practice.models.timeoff.TimeOff.Type['HOLIDAY'], 'Feiertag / Public Holiday'), (my_practice.models.timeoff.TimeOff.Type['SICK'], 'Krank / Sick Leave'), (my_practice.models.timeoff.TimeOff.Type['TRAINING'], 'Fortbildung / Training'), (my_practice.models.timeoff.TimeOff.Type['OTHER'], 'Sonstiges / Other')], default='vacation', max_length=20, verbose_name='Type')),
                ('title', models.CharField(help_text="Brief description (e.g., 'Sommerurlaub', 'Weihnachten')", max_length=200, verbose_name='Title')),
                ('notes', models.TextField(blank=True, help_text='Additional information or reminders', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Time Off',
                'verbose_name_plural': 'Time Off Periods',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_type', models.CharField(choices=[(my_practice.models.operational.OperationalChecklistCompletion.ChecklistType['WEEKLY'], 'Weekly backup'), (my_practice.models.operational.OperationalChecklistCompletion.ChecklistType['MONTHLY'], 'Monthly restore test'), (my_practice.models.operational.OperationalChecklistCompletion.ChecklistType['QUARTERLY'], 'MicroSD offsite backup (card A/B alternating, every 2 weeks)'), (my_practice.models.operational.OperationalChecklistCompletion.ChecklistType['ANNUAL'], 'Annual security review')], max_length=20, verbose_name='Checklist type')),
                ('item_id', models.CharField(help_text="Matches the item id in CHECKLIST_ITEMS (e.g. 'pick_card')", max_length=50, verbose_name='Item ID')),
                ('reason', models.TextField(help_text='Why is this step paused?', verbose_name='Reason')),
                ('paused_until', models.DateField(blank=True, help_text='Empty = indefinite. Date = pause expires automatically.', null=True, verbose_name='Paused until')),
            ],
            options={
                'verbose_name': 'Checklist pause',
                'verbose_name_plural': 'Checklist pauses',
                'unique_together': {('checklist_type', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[(my_practice.models.client.ClientDocument.DocumentType['INTRO_NOTES'], 'Intro meeting (notes)'), (my_practice.models.client.ClientDocument.DocumentType['INTAKE'], 'Intake form'), (my_practice.models.client.ClientDocument.DocumentType['ANAMNESE'], 'Anamnesis questionnaire'), (my_practice.models.client.ClientDocument.DocumentType['CONTRACT'], 'Treatment contract'), (my_practice.models.client.ClientDocument.DocumentType['REFERRAL'], 'Referral'), (my_practice.models.client.ClientDocument.DocumentType['OTHER'], 'Other')], default=my_practice.models.client.ClientDocument.DocumentType['OTHER'], max_length=20, verbose_name='Document type')),
                ('file', models.FileField(help_text='PDF, JPG, PNG or DOCX', upload_to=my_practice.models.client.client_document_upload_path, verbose_name='File')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('document_date', models.DateField(default=django.utils.timezone.localdate, help_text='Date of the document (e.g. signing date)', verbose_name='Document date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='my_practice.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client document',
                'verbose_name_plural': 'Client documents',
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intake_notes', my_practice.fields.EncryptedTextField(blank=True, help_text='Initial session + clinical assessment (encrypted)', verbose_name='Intake & anamnesis')),
                ('case_notes', my_practice.fields.EncryptedTextField(blank=True, help_text='Themes, dynamics, challenges, future work (encrypted)', verbose_name='Case notes')),
                ('arbeitsdiagnose', my_practice.fields.EncryptedCharField(blank=True, help_text='Clinical working diagnosis (encrypted)', verbose_name='Working diagnosis')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='my_practice.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client profile',
                'verbose_name_plural': 'Client profiles',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for organizing and categorizing clients', related_name='clients', to='my_practice.clienttag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='ExpenseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF, JPG or PNG of the receipt / invoice', upload_to=my_practice.models.financial.expense_attachment_upload_path, verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='my_practice.companyexpense', verbose_name='Expense')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Auto-generated (e.g., JL-5) or enter manually', max_length=20, unique=True, verbose_name='Invoice number')),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate, help_text='Defaults to today', verbose_name='Invoice date')),
                ('status', models.CharField(choices=[(my_practice.models.invoice.Invoice.Status['DRAFT'], 'Draft'), (my_practice.models.invoice.Invoice.Status['SENT'], 'Sent'), (my_practice.models.invoice.Invoice.Status['PAID'], 'Paid'), (my_practice.models.invoice.Invoice.Status['CANCELLED'], 'Cancelled'), (my_practice.models.invoice.Invoice.Status['WRITTEN_OFF'], 'Written off')], default=my_practice.models.invoice.Invoice.Status['DRAFT'], max_length=20, verbose_name='Status')),
                ('paid_date', models.DateField(blank=True, help_text='Date of payment', null=True, verbose_name='Paid on')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Kleinunternehmer = 0%', max_digits=5, verbose_name='Tax rate (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tax amount')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total amount')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='my_practice.client', verbose_name='Client')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='my_practice.practice', verbose_name='Practice')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='OperationalChecklistCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(choices=[(my_practice.models.operational.OperationalChecklistCompletion.ChecklistType['WEEKLY'], 'Weekly backup'), (my_practice.models.operational.OperationalChecklistCompletion.ChecklistType['MONTHLY'], 'Monthly restore test'), (my_practice.models.operational.OperationalChecklistCompletion.ChecklistType['QUARTERLY'], 'MicroSD offsite backup (card A/B alternating, every 2 weeks)'), (my_practice.models.operational.OperationalChecklistCompletion.ChecklistType['ANNUAL'], 'Annual security review')], max_length=20, verbose_name='Checklist type')),
                ('year_month', models.DateField(help_text='First day of the period (e.g. 2026-03-01 for March 2026)', verbose_name='Period')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed on')),
                ('notes', models.TextField(blank=True, help_text='e.g. "Restore test OK, 676 invoices verified"', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Checklist completion',
                'verbose_name_plural': 'Checklist completions',
                'ordering': ['-year_month', 'checklist_type'],
                'unique_together': {('checklist_type', 'year_month')},
            },
        ),
        migrations.CreateModel(
            name='MarketingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='From')),
                ('end_date', models.DateField(blank=True, help_text='Leave empty if still active', null=True, verbose_name='To')),
                ('description', models.CharField(help_text='e.g. "Google Ads €5/day" or "It\'s Complicated Premium"', max_length=500, verbose_name='Description')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_periods', to='my_practice.practice', verbose_name='Practice')),
            ],
            options={
                'verbose_name': 'Marketing period',
                'verbose_name_plural': 'Marketing periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.TextField(help_text='Encrypted OAuth2 token JSON')),
                ('refresh_token', models.TextField(blank=True, help_text='Refresh token for token renewal')),
                ('token_uri', models.CharField(default='https://oauth2.googleapis.com/token', max_length=500)),
                ('client_id', models.CharField(max_length=500)),
                ('client_secret', models.CharField(max_length=500)),
                ('scopes', models.JSONField(default=list, help_text='List of granted scopes')),
                ('calendar_id', models.CharField(blank=True, help_text='Google Calendar selected for session import', max_length=500, verbose_name='Calendar')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Token expiration time', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is currently active')),
                ('practice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_tokens', to='my_practice.practice', verbose_name='Practice')),
            ],
            options={
                'verbose_name': 'Google Calendar Token',
                'verbose_name_plural': 'Google Calendar Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_key', models.CharField(help_text="Normalized IBAN ('iban:...') or payer name ('name:...') used to match future transactions", max_length=200, verbose_name='Counterparty')),
                ('category', models.CharField(choices=[(my_practice.models.financial.CompanyExpense.Category['MIETE'], 'Rent'), (my_practice.models.financial.CompanyExpense.Category['TELEFON'], 'Phone'), (my_practice.models.financial.CompanyExpense.Category['VERBAND'], 'Association / membership fees'), (my_practice.models.financial.CompanyExpense.Category['VERSICHERUNG'], 'Insurance'), (my_practice.models.financial.CompanyExpense.Category['KONTO'], 'Account / account fees'), (my_practice.models.financial.CompanyExpense.Category['WEBSEITE'], 'Website / domain'), (my_practice.models.financial.CompanyExpense.Category['WERBUNG'], 'Advertising / marketing'), (my_practice.models.financial.CompanyExpense.Category['SOFTWARE'], 'Software'), (my_practice.models.financial.CompanyExpense.Category['SELBSTERFAHRUNG'], 'Personal therapy (training)'), (my_practice.models.financial.CompanyExpense.Category['SUPERVISION'], 'Supervision'), (my_practice.models.financial.CompanyExpense.Category['TRAINING'], 'Training / continuing education'), (my_practice.models.financial.CompanyExpense.Category['AUSBILDUNG_ORT'], 'Training location'), (my_practice.models.financial.CompanyExpense.Category['GRUPPE'], 'Group'), (my_practice.models.financial.CompanyExpense.Category['MATERIALIEN'], 'Materials'), (my_practice.models.financial.CompanyExpense.Category['HARDWARE'], 'Hardware'), (my_practice.models.financial.CompanyExpense.Category['LITERATUR'], 'Literature'), (my_practice.models.financial.CompanyExpense.Category['KONGRESS'], 'Conference'), (my_practice.models.financial.CompanyExpense.Category['OTHER'], 'Other')], max_length=30, verbose_name='Category')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_category_rules', to='my_practice.practice', verbose_name='Practice')),
            ],
            options={
                'verbose_name': 'Expense category rule',
                'verbose_name_plural': 'Expense category rules',
            },
        ),
        migrations.CreateModel(
            name='CompanyWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negative amount for corrections/reversals', max_digits=10, verbose_name='Amount')),
                ('description', models.TextField(blank=True, help_text='Optional: purpose', verbose_name='Notes')),
                ('category', models.CharField(choices=[(my_practice.models.financial.CompanyWithdrawal.Category['SALARY'], 'Salary / personal'), (my_practice.models.financial.CompanyWithdrawal.Category['TAX'], 'Tax prepayment'), (my_practice.models.financial.CompanyWithdrawal.Category['PRIVATE_TRANSFER'], 'Private transfer'), (my_practice.models.financial.CompanyWithdrawal.Category['OTHER'], 'Other'), (my_practice.models.financial.CompanyWithdrawal.Category['CONTRIBUTION'], 'Capital contribution'), (my_practice.models.financial.CompanyWithdrawal.Category['CORRECTION'], 'Incorrect posting / correction')], default=my_practice.models.financial.CompanyWithdrawal.Category['SALARY'], max_length=20, verbose_name='Category')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='my_practice.practice', verbose_name='Practice')),
            ],
            options={
                'verbose_name': 'Company Withdrawal',
                'verbose_name_plural': 'Company Withdrawals',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='companyexpense',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='my_practice.practice', verbose_name='Practice'),
        ),
        migrations.CreateModel(
            name='ClientInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('source', models.CharField(choices=[(my_practice.models.inquiry.InquirySource['GOOGLE_ADS'], 'Google Ads'), (my_practice.models.inquiry.InquirySource['GOOGLE_ORGANIC'], 'Google (organic)'), (my_practice.models.inquiry.InquirySource['WEBSITE'], 'Website'), (my_practice.models.inquiry.InquirySource['REFERRAL'], 'Referral'), (my_practice.models.inquiry.InquirySource['DIRECTORY'], 'Therapist directory'), (my_practice.models.inquiry.InquirySource['ITS_COMPLICATED'], "It's Complicated"), (my_practice.models.inquiry.InquirySource['NETWORK'], 'Network / colleagues'), (my_practice.models.inquiry.InquirySource['OTHER'], 'Other')], max_length=20, verbose_name='Source')),
                ('status', models.CharField(choices=[(my_practice.models.inquiry.InquiryStatus['NEW'], 'New'), (my_practice.models.inquiry.InquiryStatus['CONTACTED'], 'Contacted'), (my_practice.models.inquiry.InquiryStatus['INTRO_MEETING'], 'Intro meeting'), (my_practice.models.inquiry.InquiryStatus['WAITLIST'], 'Waitlist'), (my_practice.models.inquiry.InquiryStatus['IN_INTAKE'], 'Intake in progress'), (my_practice.models.inquiry.InquiryStatus['CONVERTED'], 'Onboarded'), (my_practice.models.inquiry.InquiryStatus['DECLINED'], 'Declined'), (my_practice.models.inquiry.InquiryStatus['UNREACHABLE'], 'Unreachable'), (my_practice.models.inquiry.InquiryStatus['NOT_SUITABLE'], 'Not a match')], default=my_practice.models.inquiry.InquiryStatus['NEW'], max_length=20, verbose_name='Status')),
                ('inquiry_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date received')),
                ('language', models.CharField(choices=[('de', 'German'), ('en', 'English')], default='de', help_text='Preferred language of the person inquiring', max_length=2, verbose_name='Language')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('initial_contact_notes', models.TextField(blank=True, help_text='Notes from the initial conversation (concerns, expectations, impressions)', verbose_name='Initial contact notes')),
                ('contacted_date', models.DateField(blank=True, help_text='Date of your first response / contact', null=True, verbose_name='Responded on')),
                ('intro_date', models.DateField(blank=True, help_text='Date of the intro meeting', null=True, verbose_name='Intro meeting on')),
                ('decision_date', models.DateField(blank=True, help_text='Date of the client decision (intake or decline / not a match)', null=True, verbose_name='Decision on')),
                ('converted_date', models.DateField(blank=True, help_text='Date of onboarding as a client', null=True, verbose_name='Onboarded on')),
                ('converted_client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_inquiry', to='my_practice.client', verbose_name='Client (after onboarding)')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='my_practice.practice', verbose_name='Practice')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-inquiry_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='practice',
            field=models.ForeignKey(help_text='Which practice this client is assigned to', on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='my_practice.practice', verbose_name='Practice'),
        ),
        migrations.CreateModel(
            name='CapacityPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Valid from')),
                ('hours_per_week', models.PositiveSmallIntegerField(help_text='Available therapy hours per week from this date', verbose_name='Hours/week')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_periods', to='my_practice.practice', verbose_name='Practice')),
            ],
            options={
                'verbose_name': 'Capacity period',
                'verbose_name_plural': 'Capacity periods',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(help_text='Transaction booking date', verbose_name='Booking date')),
                ('value_date', models.DateField(help_text='Value date', verbose_name='Value date')),
                ('payer_name', models.CharField(help_text='Name of payer/payee', max_length=200, verbose_name='Payer/payee name')),
                ('payer_iban', models.CharField(blank=True, max_length=34, verbose_name='Payer/payee IBAN')),
                ('reference', models.TextField(help_text='Payment reference text', verbose_name='Payment reference')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (positive=income, negative=expense)', max_digits=10, verbose_name='Amount')),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Account balance after transaction', max_digits=10, verbose_name='Balance after transaction')),
                ('match_confidence', models.CharField(choices=[(my_practice.models.bank_statement.BankTransaction.Confidence['EXACT'], 'Exact Match'), (my_practice.models.bank_statement.BankTransaction.Confidence['FUZZY'], 'Fuzzy Match (±5€)'), (my_practice.models.bank_statement.BankTransaction.Confidence['MANUAL'], 'Manual Assignment'), (my_practice.models.bank_statement.BankTransaction.Confidence['IGNORED'], 'Ignored (Expense/Duplicate)'), (my_practice.models.bank_statement.BankTransaction.Confidence['UNMATCHED'], 'Unmatched'), (my_practice.models.bank_statement.BankTransaction.Confidence['AUTO_WITHDRAWAL'], 'Auto-Created Withdrawal'), (my_practice.models.bank_statement.BankTransaction.Confidence['AUTO_EXPENSE'], 'Auto-Created Expense'), (my_practice.models.bank_statement.BankTransaction.Confidence['AUTO_CONTRIBUTION'], 'Auto-Created Contribution (Kapitaleinlage)'), (my_practice.models.bank_statement.BankTransaction.Confidence['AUTO_CORRECTION'], 'Auto-Created Correction (Fehlbuchung)')], default='unmatched', max_length=20, verbose_name='Match confidence')),
                ('extracted_invoice_number', models.CharField(blank=True, help_text='Invoice number extracted from reference text', max_length=20, verbose_name='Extracted invoice number')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Imported on')),
                ('processed', models.BooleanField(default=False, help_text='Whether transaction has been processed/matched', verbose_name='Processed')),
                ('notes', models.TextField(blank=True, help_text='Manual notes about this transaction', verbose_name='Notes')),
                ('account_iban', models.CharField(blank=True, help_text='IBAN of the source account from the CSV export – must match the practice IBAN', max_length=34, verbose_name='Account IBAN')),
                ('linked_expense', models.ForeignKey(blank=True, help_text='CompanyExpense auto-created or manually assigned for this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='my_practice.companyexpense', verbose_name='Linked expense')),
                ('linked_withdrawal', models.ForeignKey(blank=True, help_text='CompanyWithdrawal auto-created or manually assigned for this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='my_practice.companywithdrawal', verbose_name='Linked withdrawal')),
                ('matched_invoice', models.ForeignKey(blank=True, help_text='Invoice this transaction was matched to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='my_practice.invoice', verbose_name='Matched invoice')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='my_practice.practice', verbose_name='Practice')),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='PracticeTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Short description of the task', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional detailed notes')),
                ('category', models.CharField(choices=[(my_practice.models.todo.PracticeTodo.Category['ADMIN'], 'Administrative'), (my_practice.models.todo.PracticeTodo.Category['LEARNING'], 'Learning/Research'), (my_practice.models.todo.PracticeTodo.Category['FINANCIAL'], 'Financial/Accounting'), (my_practice.models.todo.PracticeTodo.Category['CLIENT'], 'Client-related'), (my_practice.models.todo.PracticeTodo.Category['PRACTICE'], 'Practice Management'), (my_practice.models.todo.PracticeTodo.Category['OTHER'], 'Other')], default='other', help_text='Task category for organization', max_length=20)),
                ('priority', models.CharField(choices=[(my_practice.models.todo.PracticeTodo.Priority['LOW'], 'Low'), (my_practice.models.todo.PracticeTodo.Priority['MEDIUM'], 'Medium'), (my_practice.models.todo.PracticeTodo.Priority['HIGH'], 'High'), (my_practice.models.todo.PracticeTodo.Priority['URGENT'], 'Urgent')], default='medium', help_text='Task priority level', max_length=10)),
                ('due_date', models.DateField(blank=True, help_text='Optional due date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was completed', null=True)),
                ('snoozed_until', models.DateField(blank=True, help_text='Hide from the focus queue until this date', null=True)),
                ('task_type', models.CharField(choices=[(my_practice.models.todo.PracticeTodo.TaskType['MANUAL'], 'Manual'), (my_practice.models.todo.PracticeTodo.TaskType['MISSING_SESSION_LOG'], 'Missing session log'), (my_practice.models.todo.PracticeTodo.TaskType['INVOICE_UNPAID'], 'Unpaid invoice'), (my_practice.models.todo.PracticeTodo.TaskType['INVOICE_UNSENT'], 'Unsent invoice'), (my_practice.models.todo.PracticeTodo.TaskType['SUPERVISION'], 'Supervision'), (my_practice.models.todo.PracticeTodo.TaskType['RECURRING_REVIEW'], 'Recurring review'), (my_practice.models.todo.PracticeTodo.TaskType['OPERATIONAL_CHECKLIST'], 'Operational checklist')], default=my_practice.models.todo.PracticeTodo.TaskType['MANUAL'], help_text='Manual entry, or a materialized system signal (unpaid invoice, missing session log, etc.)', max_length=30)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Related object type, for materialized tasks (e.g. Client, Invoice)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='todos', to='my_practice.practice', verbose_name='Practice')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal identifier (e.g., therapy_60, therapy_90)', max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Display name (e.g., "60-Min Therapy Session")', max_length=255, verbose_name='Name (Default)')),
                ('name_de', models.CharField(blank=True, help_text='German name (e.g., "Psychotherapie, 60 Min.")', max_length=255, verbose_name='Name (German)')),
                ('name_en', models.CharField(blank=True, help_text='English name (e.g., "60-Min Therapy Session")', max_length=255, verbose_name='Name (English)')),
                ('default_duration', models.IntegerField(default=60, verbose_name='Default duration (minutes)')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_types', to='my_practice.practice', verbose_name='Practice')),
            ],
            options={
                'verbose_name': 'Service type',
                'verbose_name_plural': 'Service types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True, verbose_name='Session date')),
                ('session_time', models.TimeField(blank=True, help_text='Session start (from calendar import)', null=True, verbose_name='Time')),
                ('duration', models.IntegerField(default=60, verbose_name='Duration (minutes)')),
                ('cancelled', models.BooleanField(db_index=True, default=False, help_text='Session was cancelled (no-show)', verbose_name='Cancelled')),
                ('group_size', models.PositiveSmallIntegerField(default=1, help_text='Number of participants (>1 for group sessions); affects therapist-hours calculation', verbose_name='Group size')),
                ('billable', models.BooleanField(db_index=True, default=True, help_text='Non-billable sessions (e.g. intro meeting) are ignored in monthly billing', verbose_name='Billable')),
                ('calendar_event_id', models.CharField(blank=True, help_text='Google Calendar event ID if imported', max_length=200, verbose_name='Calendar event ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='my_practice.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-session_date', '-session_time'],
            },
        ),
        migrations.CreateModel(
            name='PendingCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=255, unique=True, verbose_name='Google Event ID')),
                ('summary', models.CharField(max_length=500, verbose_name='Summary')),
                ('event_date', models.DateField(verbose_name='Date')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('duration_minutes', models.IntegerField(verbose_name='Duration (minutes)')),
                ('status', models.CharField(choices=[(my_practice.models.calendar.PendingCalendarEvent.Status['PENDING'], 'Pending'), (my_practice.models.calendar.PendingCalendarEvent.Status['IMPORTED'], 'Imported'), (my_practice.models.calendar.PendingCalendarEvent.Status['SKIPPED'], 'Skipped'), (my_practice.models.calendar.PendingCalendarEvent.Status['CANCELLED'], 'Cancelled')], default=my_practice.models.calendar.PendingCalendarEvent.Status['PENDING'], max_length=20, verbose_name='Status')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Fetched on')),
                ('missing_since', models.DateTimeField(blank=True, help_text='First fetch where the event was no longer found in the calendar', null=True, verbose_name='Missing since')),
                ('matched_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_calendar_events', to='my_practice.client', verbose_name='Client')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_calendar_events', to='my_practice.practice', verbose_name='Practice')),
                ('suggested_service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_calendar_events', to='my_practice.servicetype', verbose_name='Service type')),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_calendar_event', to='my_practice.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Pending calendar event',
                'verbose_name_plural': 'Pending calendar events',
                'ordering': ['event_date', 'event_time'],
            },
        ),
        migrations.CreateModel(
            name='Leistungserfassung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('betrag', models.DecimalField(decimal_places=2, help_text='= maximum rate of the billing code at the time of entry', max_digits=8, verbose_name='GebüH amount (€)')),
                ('vereinbarter_betrag', models.DecimalField(decimal_places=2, help_text='Fee for the session (hourly_rate × duration/60), frozen at entry time', max_digits=8, verbose_name='Agreed amount (€)')),
                ('ziffer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leistungen', to='my_practice.gebuhziffer', verbose_name='GebüH billing code')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gebueh_leistungen', to='my_practice.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Service entry',
                'verbose_name_plural': 'Service entries',
                'ordering': ['session__session_date', 'ziffer__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Rate')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantity')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('group_size', models.PositiveSmallIntegerField(default=1, help_text='Number of participants for group offerings (default 1 = individual session). Affects the calculation of therapist hours in analytics.', verbose_name='Group size')),
                ('description', models.CharField(blank=True, help_text='Free-text line item label, used instead of a linked session (day-rate/project billing) — only available when the practice allows free-form invoice items', max_length=255, verbose_name='Description')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='my_practice.invoice', verbose_name='Invoice')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_practice.servicetype', verbose_name='Service Type')),
                ('session', models.ForeignKey(blank=True, help_text='Linked session (central reference for clinical documentation + billing)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='my_practice.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Invoice item',
                'verbose_name_plural': 'Invoice items',
                'ordering': ['session__session_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(choices=[('erstgespraech', 'Initial session'), ('standard', 'Standard'), ('krisenintervention', 'Crisis intervention'), ('abschlussphase', 'Closing phase'), ('ausfall', 'No-show / cancellation')], default='standard', max_length=30, verbose_name='Session type')),
                ('mood_tags', models.JSONField(default=list, help_text='Selection from predefined signals (unencrypted, for triage)', verbose_name='Mood tags')),
                ('summary', models.CharField(blank=True, default='', help_text='One-liner for the overview (unencrypted, max. 120 characters)', max_length=120, verbose_name='Short summary')),
                ('content', my_practice.fields.EncryptedTextField(blank=True, help_text='Pre-filled: feeling afterward / perception / session / what helped (encrypted)', verbose_name='Session note')),
                ('interventions', my_practice.fields.EncryptedTextField(blank=True, help_text='Techniques and interventions applied (encrypted)', verbose_name='Interventions')),
                ('therapist_reflection', my_practice.fields.EncryptedTextField(blank=True, help_text='How I felt about it — countertransference (encrypted, separate)', verbose_name='Own reflection')),
                ('next_session_ideas', my_practice.fields.EncryptedTextField(blank=True, help_text='Themes, interventions, homework for the next session (encrypted)', verbose_name='Ideas for next session')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='my_practice.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Session log',
                'verbose_name_plural': 'Session logs',
                'ordering': ['-session__session_date'],
            },
        ),
        migrations.CreateModel(
            name='SupervisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', my_practice.fields.EncryptedTextField(help_text='Supervision question or topic (encrypted)', verbose_name='Content')),
                ('status', models.CharField(choices=[('offen', 'Open'), ('besprochen', 'Discussed')], default='offen', max_length=20, verbose_name='Status')),
                ('resolution_notes', my_practice.fields.EncryptedTextField(blank=True, default='', help_text='Feedback or outcome once discussed (optional, encrypted)', verbose_name='Resolution notes')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='Discussed on')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision_items', to='my_practice.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Supervision topic',
                'verbose_name_plural': 'Supervision topics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxYearNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='Tax year')),
                ('allocation_note', models.TextField(blank=True, help_text='Documented split key, e.g. "Revenue share 95/5 for 2025 — HO allowance and commuter allowance split accordingly."', verbose_name='Allocation note')),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Positive = back payment to the tax office, negative = refund from the tax office', max_digits=10, null=True, verbose_name='Tax back payment / refund')),
                ('settlement_date', models.DateField(blank=True, help_text='Date of the tax assessment notice', null=True, verbose_name='Assessment date')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_year_notes', to='my_practice.practice', verbose_name='Practice')),
            ],
            options={
                'verbose_name': 'Tax year note',
                'verbose_name_plural': 'Tax year notes',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='UserPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, help_text='Owners have full administrative rights', verbose_name='Owner')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='my_practice.practice', verbose_name='Practice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User-practice assignment',
                'verbose_name_plural': 'User-practice assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='practice',
            name='users',
            field=models.ManyToManyField(related_name='practices', through='my_practice.UserPractice', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.CreateModel(
            name='ClientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias_name', models.CharField(help_text='Name as it appears on bank statements', max_length=200, verbose_name='Bank name')),
                ('notes', models.TextField(blank=True, help_text="e.g. 'Parent pays' or 'Former surname'", verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_aliases', to='my_practice.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client alias',
                'verbose_name_plural': 'Client aliases',
                'ordering': ['client', 'alias_name'],
                'indexes': [models.Index(fields=['alias_name'], name='my_practice_alias_n_509cfa_idx')],
                'unique_together': {('client', 'alias_name')},
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_date', models.DateField(help_text='Date of the entry (e.g. call, note)', verbose_name='Date')),
                ('content', my_practice.fields.EncryptedTextField(help_text='Note content (encrypted, markdown supported)', verbose_name='Content')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='my_practice.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Client note',
                'verbose_name_plural': 'Client notes',
                'ordering': ['-note_date', '-created_at'],
                'indexes': [models.Index(fields=['client', 'note_date'], name='clientnote_client_date_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoice_invoice_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['paid_date'], name='invoice_paid_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='invoice_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-invoice_date', 'status'], name='invoice_date_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('invoice_number',), name='unique_invoice_number', violation_error_message='This invoice number already exists.'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategoryrule',
            unique_together={('practice', 'match_key')},
        ),
        migrations.AddIndex(
            model_name='companywithdrawal',
            index=models.Index(fields=['date'], name='withdrawal_date_idx'),
        ),
        migrations.AddIndex(
            model_name='companyexpense',
            index=models.Index(fields=['date'], name='expense_date_idx'),
        ),
        migrations.AddIndex(
            model_name='companyexpense',
            index=models.Index(fields=['category'], name='expense_category_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinquiry',
            index=models.Index(fields=['status'], name='inquiry_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='capacityperiod',
            unique_together={('practice', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['practice', 'transaction_date'], name='my_practice_practic_78a6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['practice', 'processed'], name='my_practice_practic_527efb_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['practice', 'match_confidence'], name='my_practice_practic_68b33d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='banktransaction',
            unique_together={('practice', 'transaction_date', 'amount', 'reference')},
        ),
        migrations.AddIndex(
            model_name='practicetodo',
            index=models.Index(fields=['practice', 'completed_at'], name='todo_prac_completed'),
        ),
        migrations.AddIndex(
            model_name='practicetodo',
            index=models.Index(fields=['practice', 'due_date'], name='todo_prac_due'),
        ),
        migrations.AddIndex(
            model_name='practicetodo',
            index=models.Index(fields=['practice', 'category'], name='todo_prac_category'),
        ),
        migrations.AddIndex(
            model_name='practicetodo',
            index=models.Index(fields=['practice', 'task_type'], name='todo_prac_task_type'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['client', 'session_date'], name='session_client_date_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingcalendarevent',
            index=models.Index(fields=['practice', 'status'], name='pce_practice_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingcalendarevent',
            index=models.Index(fields=['matched_client', 'event_date'], name='pce_client_date_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisionitem',
            index=models.Index(fields=['client', 'status'], name='supervision_client_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxyearnote',
            unique_together={('practice', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='userpractice',
            unique_together={('user', 'practice')},
        ),
    ]
