# Generated by Django 6.0.6 on 2026-06-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
