# Generated by Django 6.0.6 on 2026-06-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_practice', '0002_widen_practice_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlog',
            name='summary',
            field=models.CharField(blank=True, default='', help_text='Einzeiler für den Überblick (unverschlüsselt, max. 120 Zeichen)', max_length=120, verbose_name='Kurzzusammenfassung'),
        ),
    ]
