# Generated by Django 6.0.6 on 2026-06-26 08:07

import my_practice.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_practice', '0003_sessionlog_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlog',
            name='next_session_ideas',
            field=my_practice.fields.EncryptedTextField(blank=True, help_text='Themen, Interventionen, Hausaufgaben für die nächste Sitzung (verschlüsselt)', verbose_name='Ideen für nächste Sitzung'),
        ),
    ]
