# Generated by Django 6.1.1 on 2026-09-15 21:57

import my_practice.models.todo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_practice', '0003_cache_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicetodo',
            name='task_type',
            field=models.CharField(choices=[(my_practice.models.todo.PracticeTodo.TaskType['MANUAL'], 'Manual'), (my_practice.models.todo.PracticeTodo.TaskType['MISSING_SESSION_LOG'], 'Missing session log'), (my_practice.models.todo.PracticeTodo.TaskType['INVOICE_UNPAID'], 'Unpaid invoice'), (my_practice.models.todo.PracticeTodo.TaskType['INVOICE_UNSENT'], 'Unsent invoice'), (my_practice.models.todo.PracticeTodo.TaskType['SUPERVISION'], 'Supervision'), (my_practice.models.todo.PracticeTodo.TaskType['RECURRING_REVIEW'], 'Recurring review'), (my_practice.models.todo.PracticeTodo.TaskType['OPERATIONAL_CHECKLIST'], 'Operational checklist'), (my_practice.models.todo.PracticeTodo.TaskType['BANK_UNMATCHED'], 'Unmatched bank transactions')], default=my_practice.models.todo.PracticeTodo.TaskType['MANUAL'], help_text='Manual entry, or a materialized system signal (unpaid invoice, missing session log, etc.)', max_length=30),
        ),
    ]
