# Generated by Django 6.0.6 on 2026-06-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0004_sessionlog_next_session_ideas"),
    ]

    operations = [
        migrations.CreateModel(
            name="GebuhZiffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nummer", models.CharField(max_length=10, unique=True, verbose_name="Ziffer")),
                ("bezeichnung", models.CharField(max_length=300, verbose_name="Bezeichnung")),
                (
                    "satz_max",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wird für die Abrechnung verwendet",
                        max_digits=8,
                        verbose_name="Höchstsatz (€)",
                    ),
                ),
                (
                    "satz_min",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Referenzwert, wird nicht abgerechnet",
                        max_digits=8,
                        verbose_name="Mindestsatz (€)",
                    ),
                ),
                (
                    "anmerkung",
                    models.TextField(
                        blank=True,
                        help_text="Abrechnungshinweise (z.B. Alleinleistung, Häufigkeitsbeschränkung)",
                        verbose_name="Anmerkung",
                    ),
                ),
                (
                    "max_haeufigkeit",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Maximale Anzahl innerhalb des Bezugszeitraums",
                        null=True,
                        verbose_name="Max. Häufigkeit",
                    ),
                ),
                (
                    "bezugszeitraum_tage",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Zeitraum in Tagen für die Häufigkeitsprüfung",
                        null=True,
                        verbose_name="Bezugszeitraum (Tage)",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Anzeigereihenfolge in der Schnellerfassung",
                        verbose_name="Reihenfolge",
                    ),
                ),
            ],
            options={
                "verbose_name": "GebüH-Ziffer",
                "verbose_name_plural": "GebüH-Ziffern",
                "ordering": ["sort_order", "nummer"],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="needs_gebueh_invoice",
            field=models.BooleanField(
                default=False,
                help_text="GebüH-Ziffern und Diagnose auf der Rechnung ausweisen (PKV / Beihilfe)",
                verbose_name="GebüH-Rechnung",
            ),
        ),
        migrations.CreateModel(
            name="Leistungserfassung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "betrag",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="= Höchstsatz der Ziffer zum Zeitpunkt der Erfassung",
                        max_digits=8,
                        verbose_name="GebüH-Betrag (€)",
                    ),
                ),
                (
                    "vereinbarter_betrag",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Honorar für die Sitzung (hourly_rate × duration/60), eingefroren bei Erfassung",
                        max_digits=8,
                        verbose_name="Vereinbarter Betrag (€)",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gebueh_leistungen",
                        to="my_practice.session",
                        verbose_name="Sitzung",
                    ),
                ),
                (
                    "ziffer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leistungen",
                        to="my_practice.gebuhziffer",
                        verbose_name="GebüH-Ziffer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leistungserfassung",
                "verbose_name_plural": "Leistungserfassungen",
                "ordering": ["session__session_date", "ziffer__sort_order"],
                "indexes": [models.Index(fields=["session"], name="leistung_session_idx")],
            },
        ),
    ]
