# Generated by Django 6.0.6 on 2026-07-04 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0006_seed_gebueh_ziffern"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacityPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Gültig ab")),
                (
                    "hours_per_week",
                    models.PositiveSmallIntegerField(
                        help_text="Verfügbare Therapiestunden pro Woche ab diesem Datum",
                        verbose_name="Stunden/Woche",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_periods",
                        to="my_practice.practice",
                        verbose_name="Praxis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kapazitätszeitraum",
                "verbose_name_plural": "Kapazitätszeiträume",
                "ordering": ["start_date"],
                "unique_together": {("practice", "start_date")},
            },
        ),
    ]
