# Generated by Django 6.0.6 on 2026-07-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0007_capacity_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxyearnote",
            name="settlement_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Positiv = Nachzahlung ans Finanzamt, negativ = Erstattung vom Finanzamt",
                max_digits=10,
                null=True,
                verbose_name="Steuernachzahlung / -erstattung",
            ),
        ),
        migrations.AddField(
            model_name="taxyearnote",
            name="settlement_date",
            field=models.DateField(
                blank=True,
                help_text="Datum des Steuerbescheids",
                null=True,
                verbose_name="Bescheiddatum",
            ),
        ),
    ]
