# Generated by Django 6.0.7, hand-adjusted: RenameField instead of the
# autodetector's Remove+Add so existing self-hosted installs keep their
# configured short_title value instead of losing it back to the default.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0012_i18n_verbose_names_batch3"),
    ]

    operations = [
        migrations.RenameField(
            model_name="practice",
            old_name="short_title",
            new_name="short_title_de",
        ),
        migrations.AlterField(
            model_name="practice",
            name="short_title_de",
            field=models.CharField(
                default="Therapie",
                help_text="Short label for the title bar, shown in the German UI (e.g. 'Therapie')",
                max_length=50,
                verbose_name="Short title (German)",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="short_title_en",
            field=models.CharField(
                blank=True,
                default="Therapy",
                help_text="Short label for the title bar, shown in the English UI (e.g. 'Therapy')",
                max_length=50,
                verbose_name="Short title (English)",
            ),
        ),
    ]
