# Generated by Django 6.0.7 on 2026-07-23 18:31

import django.db.models.deletion
import my_practice.models.todo
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("my_practice", "0013_practice_short_title_de_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicetodo",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Related object type, for materialized tasks (e.g. Client, Invoice)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="practicetodo",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="practicetodo",
            name="snoozed_until",
            field=models.DateField(
                blank=True, help_text="Hide from the focus queue until this date", null=True
            ),
        ),
        migrations.AddField(
            model_name="practicetodo",
            name="task_type",
            field=models.CharField(
                choices=[
                    (my_practice.models.todo.PracticeTodo.TaskType["MANUAL"], "Manual"),
                    (
                        my_practice.models.todo.PracticeTodo.TaskType["MISSING_SESSION_LOG"],
                        "Missing session log",
                    ),
                    (
                        my_practice.models.todo.PracticeTodo.TaskType["INVOICE_UNPAID"],
                        "Unpaid invoice",
                    ),
                    (
                        my_practice.models.todo.PracticeTodo.TaskType["INVOICE_UNSENT"],
                        "Unsent invoice",
                    ),
                    (my_practice.models.todo.PracticeTodo.TaskType["SUPERVISION"], "Supervision"),
                    (
                        my_practice.models.todo.PracticeTodo.TaskType["RECURRING_REVIEW"],
                        "Recurring review",
                    ),
                    (
                        my_practice.models.todo.PracticeTodo.TaskType["OPERATIONAL_CHECKLIST"],
                        "Operational checklist",
                    ),
                ],
                default=my_practice.models.todo.PracticeTodo.TaskType["MANUAL"],
                help_text="Manual entry, or a materialized system signal (unpaid invoice, missing session log, etc.)",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="practicetodo",
            index=models.Index(fields=["practice", "task_type"], name="todo_prac_task_type"),
        ),
    ]
