# Generated by Django 6.0.7 on 2026-07-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0014_add_task_fields_to_practicetodo"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="csv_column_account_iban",
            field=models.CharField(
                default="IBAN Auftragskonto",
                help_text="Header name of the source account IBAN column in your bank's CSV export, used to verify the file belongs to this practice's account",
                max_length=100,
                verbose_name="CSV column: account IBAN",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="csv_column_amount",
            field=models.CharField(
                default="Betrag",
                help_text="Header name of the transaction amount column in your bank's CSV export",
                max_length=100,
                verbose_name="CSV column: amount",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="csv_column_balance",
            field=models.CharField(
                default="Saldo nach Buchung",
                help_text="Header name of the running balance column in your bank's CSV export",
                max_length=100,
                verbose_name="CSV column: balance after transaction",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="csv_column_date",
            field=models.CharField(
                default="Buchungstag",
                help_text="Header name of the booking date column in your bank's CSV export",
                max_length=100,
                verbose_name="CSV column: booking date",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="csv_column_payer_iban",
            field=models.CharField(
                default="IBAN Zahlungsbeteiligter",
                help_text="Header name of the payer/payee IBAN column in your bank's CSV export",
                max_length=100,
                verbose_name="CSV column: payer/payee IBAN",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="csv_column_payer_name",
            field=models.CharField(
                default="Name Zahlungsbeteiligter",
                help_text="Header name of the payer/payee name column in your bank's CSV export",
                max_length=100,
                verbose_name="CSV column: payer/payee name",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="csv_column_reference",
            field=models.CharField(
                default="Verwendungszweck",
                help_text="Header name of the payment reference column in your bank's CSV export",
                max_length=100,
                verbose_name="CSV column: payment reference",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="csv_column_value_date",
            field=models.CharField(
                default="Valutadatum",
                help_text="Header name of the value date column in your bank's CSV export",
                max_length=100,
                verbose_name="CSV column: value date",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="csv_delimiter",
            field=models.CharField(
                default=";",
                help_text="Column separator used by your bank's CSV export, e.g. ';' or ','",
                max_length=1,
                verbose_name="CSV delimiter",
            ),
        ),
    ]
