# Generated by Django 6.0.7 on 2026-07-24 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0015_practice_csv_import_config"),
        ("my_practice", "0015_retire_missing_session_log_tag"),
    ]

    operations = []
