# Generated by Django 6.0.7 on 2026-07-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0016_merge_20260724_1010"),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="overdue_after_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Days after the invoice date before a sent invoice is flagged as overdue (dashboard widget, Focus Queue).",
                verbose_name="Overdue after (days)",
            ),
        ),
    ]
