# Generated by Django 6.0.7 on 2026-07-29 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0017_practice_overdue_after_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practicetodo",
            name="is_focus",
        ),
    ]
