# Generated by Django 6.0.7 on 2026-07-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0018_remove_practicetodo_is_focus"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="gebueh_no_diagnosis",
            field=models.BooleanField(
                default=False,
                help_text="Omit the diagnosis line from GebüH invoices for this client",
                verbose_name="No diagnosis on invoice",
            ),
        ),
    ]
