# Generated by Django 6.0.7 on 2026-08-06 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0019_gebueh_no_diagnosis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdocument",
            name="document_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Date of the document (e.g. signing date)",
                verbose_name="Document date",
            ),
        ),
        migrations.AlterField(
            model_name="clientinquiry",
            name="inquiry_date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Date received"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Defaults to today",
                verbose_name="Invoice date",
            ),
        ),
    ]
