# Generated by Django 6.0.7 on 2026-08-06 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0020_alter_clientdocument_document_date_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="leistungserfassung",
            name="leistung_session_idx",
        ),
    ]
