# Generated by Django 6.0.7 on 2026-08-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0022_tax_year_note_timestamped"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Free-text line item label, used instead of a linked session (day-rate/project billing) — only available when the practice allows free-form invoice items",
                max_length=255,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="practice",
            name="allows_free_form_items",
            field=models.BooleanField(
                default=False,
                help_text="Lets invoice items skip the linked session and use a free-text description instead — for day-rate or project billing that isn't tied to a therapy/coaching session. Leave off for therapy/coaching practices, where every invoice item must stay linked to a session.",
                verbose_name="Allow free-form invoice items",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked session (central reference for clinical documentation + billing)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_items",
                to="my_practice.session",
                verbose_name="Session",
            ),
        ),
    ]
