# Generated by Django 6.0.7 on 2026-08-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0023_p122_free_form_invoice_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practice",
            name="memberships_de",
            field=models.TextField(blank=True, default="", verbose_name="Memberships (German)"),
        ),
    ]
