# Generated by Django 6.0.7 on 2026-08-11 13:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0024_alter_practice_memberships_de"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Quantity",
            ),
        ),
    ]
