# Generated by Django 6.0.7 on 2026-08-11 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0025_alter_invoiceitem_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoiceitem",
            options={
                "ordering": ["session__session_date", "pk"],
                "verbose_name": "Invoice item",
                "verbose_name_plural": "Invoice items",
            },
        ),
    ]
