# Generated by Django 6.0.7 on 2026-08-13 11:47

import django.db.models.deletion
import my_practice.models.financial
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0026_alter_invoiceitem_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategoryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "match_key",
                    models.CharField(
                        help_text="Normalized IBAN ('iban:...') or payer name ('name:...') used to match future transactions",
                        max_length=200,
                        verbose_name="Counterparty",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (my_practice.models.financial.CompanyExpense.Category["MIETE"], "Rent"),
                            (
                                my_practice.models.financial.CompanyExpense.Category["TELEFON"],
                                "Phone",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category["VERBAND"],
                                "Association / membership fees",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category[
                                    "VERSICHERUNG"
                                ],
                                "Insurance",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category["KONTO"],
                                "Account / account fees",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category["WEBSEITE"],
                                "Website / domain",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category["WERBUNG"],
                                "Advertising / marketing",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category["SOFTWARE"],
                                "Software",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category[
                                    "SELBSTERFAHRUNG"
                                ],
                                "Personal therapy (training)",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category["SUPERVISION"],
                                "Supervision",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category["TRAINING"],
                                "Training / continuing education",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category[
                                    "AUSBILDUNG_ORT"
                                ],
                                "Training location",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category["GRUPPE"],
                                "Group",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category["MATERIALIEN"],
                                "Materials",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category["HARDWARE"],
                                "Hardware",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category["LITERATUR"],
                                "Literature",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category["KONGRESS"],
                                "Conference",
                            ),
                            (
                                my_practice.models.financial.CompanyExpense.Category["OTHER"],
                                "Other",
                            ),
                        ],
                        max_length=30,
                        verbose_name="Category",
                    ),
                ),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_category_rules",
                        to="my_practice.practice",
                        verbose_name="Practice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense category rule",
                "verbose_name_plural": "Expense category rules",
                "unique_together": {("practice", "match_key")},
            },
        ),
    ]
