# Generated by Django 6.1 on 2026-08-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_practice", "0032_cache_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendartoken",
            name="calendar_id",
            field=models.CharField(
                blank=True,
                help_text="Google Calendar selected for session import",
                max_length=500,
                verbose_name="Calendar",
            ),
        ),
    ]
