"""
Tests for invoice model validation.
"""

from datetime import date, timedelta
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.test import TestCase

from ..models import Client, Invoice, Practice, ServiceType


class InvoiceValidationTests(TestCase):
    """Test invoice model validation"""

    def setUp(self):
        """Create test fixtures"""
        # Create practice
        self.practice = Practice.objects.create(
            name="Test Practice",
            slug="invoice_validation-1",
            title="Test Practitioner",
            email="test@practice.com",
            city="Berlin",
        )

        self.client = Client.objects.create(
            client_code="TEST",
            full_name="Test Client",
            email="test@example.com",
            language="de",
            hourly_rate_60=Decimal("90.00"),
            hourly_rate_90=Decimal("130.00"),
            practice=self.practice,
        )

        self.service_type = ServiceType.objects.create(
            code="test_service",
            name="Test Service",
            name_de="Test Service DE",
            name_en="Test Service EN",
            default_duration=60,
            practice=self.practice,
        )

    def test_duplicate_invoice_number_raises_error(self):
        """Test that duplicate invoice numbers raise ValidationError"""
        # Create practice
        self.practice = Practice.objects.create(
            name="Test Practice",
            slug="test-practice",
            title="Test Practitioner",
            email="test@practice.com",
            city="Berlin",
        )

        # Create first invoice
        Invoice.objects.create(
            client=self.client,
            invoice_number="TEST-1",
            invoice_date=date.today(),
            status="draft",
            total=Decimal("90.00"),
            practice=self.practice,
        )

        # Try to create second invoice with same number
        duplicate = Invoice(
            client=self.client,
            invoice_number="TEST-1",
            invoice_date=date.today(),
            status="draft",
            total=Decimal("90.00"),
        )

        with self.assertRaises(ValidationError) as cm:
            duplicate.save()

        # Check error message
        self.assertIn("invoice_number", cm.exception.message_dict)
        self.assertIn("existiert bereits", str(cm.exception))

    def test_unique_invoice_numbers_work(self):
        """Test that different invoice numbers work fine"""
        Invoice.objects.create(
            client=self.client,
            invoice_number="TEST-1",
            invoice_date=date.today(),
            status="draft",
            total=Decimal("90.00"),
            practice=self.practice,
        )

        # Different number should work
        invoice2 = Invoice.objects.create(
            client=self.client,
            invoice_number="TEST-2",
            invoice_date=date.today(),
            status="draft",
            total=Decimal("90.00"),
            practice=self.practice,
        )

        self.assertEqual(invoice2.invoice_number, "TEST-2")

    def test_paid_date_before_invoice_date_raises_error(self):
        """Test that paid_date before invoice_date raises ValidationError"""
        invoice = Invoice(
            client=self.client,
            invoice_number="TEST-3",
            invoice_date=date.today(),
            paid_date=date.today() - timedelta(days=5),
            status="paid",
            total=Decimal("90.00"),
        )

        with self.assertRaises(ValidationError) as cm:
            invoice.save()

        self.assertIn("paid_date", cm.exception.message_dict)
        self.assertIn("nicht vor dem Rechnungsdatum", str(cm.exception))

    def test_paid_date_after_invoice_date_works(self):
        """Test that paid_date after invoice_date works"""
        invoice = Invoice.objects.create(
            client=self.client,
            invoice_number="TEST-4",
            invoice_date=date.today(),
            paid_date=date.today() + timedelta(days=5),
            status="paid",
            total=Decimal("90.00"),
            practice=self.practice,
        )

        self.assertEqual(invoice.status, "paid")
        self.assertIsNotNone(invoice.paid_date)

    def test_empty_invoice_number_allowed_for_autogeneration(self):
        """Test that empty invoice_number is allowed (will be auto-generated)"""
        invoice = Invoice.objects.create(
            client=self.client,
            invoice_number="",  # Empty = will be auto-generated by view
            invoice_date=date.today(),
            status="draft",
            total=Decimal("90.00"),
            practice=self.practice,
        )

        # Should save successfully even with empty number
        self.assertIsNotNone(invoice.pk)

    def test_update_existing_invoice_with_same_number_works(self):
        """Test that updating an invoice with its own number works"""
        invoice = Invoice.objects.create(
            client=self.client,
            invoice_number="TEST-5",
            invoice_date=date.today(),
            status="draft",
            total=Decimal("90.00"),
            practice=self.practice,
        )

        # Update the invoice with same number
        invoice.status = "sent"
        invoice.save()  # Should not raise ValidationError

        self.assertEqual(invoice.status, "sent")
